// src/components/layout/Footer.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { HeartHandshake, Phone, Mail } from '@lucide/vue'
import { useVolunteerModalStore } from '@/stores/useVolunteerModalStore'
import { CONTACT_EMAIL, TRUST_PHONE, TRUST_PHONE_TEL } from '@/lib/constants/contact'

const { t } = useI18n()
const modalStore = useVolunteerModalStore()
const year = new Date().getFullYear()
</script>

<template>
  <footer class="bg-[var(--surface-muted)] border-t border-[var(--border-default)] pt-12 pb-8 text-[var(--fg-muted)]">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div
        class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-8 pb-10 border-b border-[var(--border-default)]"
      >
        <!-- Brand column -->
        <div class="sm:col-span-2 space-y-4">
          <div class="flex items-center gap-3">
            <img src="/logo.png" alt="Smart Inclusive" class="h-9 w-auto object-contain" />
            <span class="font-extrabold text-xl text-[var(--fg)] tracking-tight font-display">
              Smart <span class="text-[var(--brand)]">Inclusive</span>
            </span>
          </div>
          <p class="text-sm text-[var(--fg-subtle)] max-w-md leading-relaxed">
            {{ t('footer.description') }}
          </p>
          <div class="pt-2">
            <button
              type="button"
              class="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[var(--brand)] text-white text-xs font-bold hover:bg-[var(--brand-hover)] transition-all cursor-pointer"
              @click="modalStore.openModal()"
            >
              <HeartHandshake class="w-4 h-4 text-amber-300" />
              <span>{{ t('nav.becomeVolunteer') }}</span>
            </button>
          </div>
        </div>

        <!-- Kids Links -->
        <div class="space-y-3">
          <h3 class="text-xs font-bold text-[var(--fg)] uppercase tracking-wider">
            {{ t('nav.kids') }}
          </h3>
          <ul class="text-sm">
            <li>
              <router-link to="/vocabulary" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.kidsItems.dictionary') }}
              </router-link>
            </li>
            <li>
              <router-link to="/etiquette" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.kidsItems.etiquette') }}
              </router-link>
            </li>
            <li>
              <router-link to="/i-can-do-it" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.kidsItems.iCan') }}
              </router-link>
            </li>
            <li>
              <router-link to="/lessons" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.kidsItems.lessons') }}
              </router-link>
            </li>
            <li>
              <router-link to="/books" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.kidsItems.books') }}
              </router-link>
            </li>
          </ul>
        </div>

        <!-- Parents & Volunteers -->
        <div class="space-y-3">
          <h3 class="text-xs font-bold text-[var(--fg)] uppercase tracking-wider">
            {{ t('footer.sections') }}
          </h3>
          <ul class="text-sm">
            <li>
              <router-link to="/for-parents" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.parents') }}
              </router-link>
            </li>
            <li>
              <router-link to="/volunteers" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.volunteers') }}
              </router-link>
            </li>
            <li>
              <router-link to="/about-project" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.aboutProject') }}
              </router-link>
            </li>
            <li>
              <router-link to="/about-us" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.aboutUs') }}
              </router-link>
            </li>
            <li>
              <router-link to="/contact" class="inline-flex min-h-[var(--tap-target-min)] items-center hover:text-[var(--brand-text)] transition-colors">
                {{ t('nav.contact') }}
              </router-link>
            </li>
          </ul>
        </div>

        <!--
          Kontaktlar (TZ 3.3). Ishonch raqami header ustidagi panelda emas,
          faqat shu yerda — panel foydalanuvchi so'roviga ko'ra olib tashlangan.
          `tel:` va `mailto:` har qanday qurilmada ishlaydi, shuning uchun
          nusxalash mantiqi bu yerda takrorlanmaydi.
        -->
        <div class="space-y-3">
          <h3 class="text-xs font-bold text-[var(--fg)] uppercase tracking-wider">
            {{ t('footer.contacts') }}
          </h3>
          <ul class="text-sm">
            <li>
              <a
                :href="TRUST_PHONE_TEL"
                class="inline-flex min-h-[var(--tap-target-min)] items-center gap-2 hover:text-[var(--brand-text)] transition-colors"
              >
                <Phone class="w-4 h-4 shrink-0" aria-hidden="true" />
                <span class="whitespace-nowrap">{{ TRUST_PHONE }}</span>
              </a>
            </li>
            <li>
              <a
                :href="`mailto:${CONTACT_EMAIL}`"
                class="inline-flex min-h-[var(--tap-target-min)] items-center gap-2 hover:text-[var(--brand-text)] transition-colors break-all"
              >
                <Mail class="w-4 h-4 shrink-0" aria-hidden="true" />
                <span>{{ CONTACT_EMAIL }}</span>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <!-- Copyright -->
      <div class="pt-6 flex flex-col sm:flex-row items-center justify-between text-xs text-[var(--fg-subtle)] gap-4">
        <p>© {{ year }} Smart Inclusive. {{ t('footer.rights') }}</p>
        <router-link to="/accessibility" class="hover:underline">
          {{ t('footer.accessibilityStatement') }}
        </router-link>
      </div>
    </div>
  </footer>
</template>

// src/components/layout/Footer.tsx
import { useTranslations } from "next-intl";
import { Link } from "@/i18n/navigation";
import {
  FOOTER_NAV,
  KIDS_NAV,
  PARENTS_NAV,
  type NavItem,
} from "@/lib/constants/navigation";
import { Container } from "@/components/ui/Container";
import { Logo } from "@/components/layout/Logo";

interface FooterColumnProps {
  titleKey: string;
  items: NavItem[];
}

function FooterColumn({ titleKey, items }: FooterColumnProps) {
  const t = useTranslations("nav");

  return (
    <div>
      <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-fg-subtle">
        {t(titleKey)}
      </h3>
      <ul className="space-y-1">
        {items.map((item) => (
          <li key={item.href}>
            <Link
              href={item.href}
              className="
                inline-flex min-h-[var(--tap-target-min)] items-center
                text-base text-fg-muted
                transition-colors duration-[var(--duration-fast)]
                hover:text-brand
              "
            >
              {t(item.labelKey)}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

/**
 * Sayt pastki qismi.
 *
 * Server Component — interaktivlik yo'q.
 *
 * QULAYLIK QARORLARI:
 *  - `<footer>` + `role` kerak emas: semantik teg o'zi landmark beradi.
 *  - Har bir ustun `<h3>` bilan nomlanadi → ekran o'quvchi sarlavhalar
 *    ro'yxati orqali tez harakatlanadi.
 *  - Havolalar ≥44px balandlikda — planshetda barmoq bilan bosish qulay.
 *  - "Qulaylik bayonoti" havolasi majburiy: platformaning qulaylik
 *    darajasi va aloqa yo'li shu yerda hujjatlashtiriladi.
 */
export function Footer() {
  const t = useTranslations("footer");
  const tSite = useTranslations("site");
  const year = new Date().getFullYear();

  return (
    <footer className="mt-auto border-t border-border bg-surface-subtle">
      <Container className="py-12">
        <div className="grid grid-cols-1 phone:grid-cols-2 tablet:grid-cols-4 gap-10">
          {/* --- Brend --- */}
          <div className="laptop:col-span-1">
            <Logo />
            <p className="mt-3 max-w-xs text-sm leading-relaxed text-fg-muted">
              {t("description")}
            </p>
          </div>

          {/* --- Bo'limlar --- */}
          <FooterColumn titleKey="kids" items={KIDS_NAV} />
          <FooterColumn titleKey="parents" items={PARENTS_NAV} />
          <FooterColumn titleKey="aboutProject" items={FOOTER_NAV} />
        </div>

        {/* --- Pastki qator --- */}
        <div
          className="
            mt-10 flex flex-wrap items-center justify-between gap-4
            border-t border-border pt-6
          "
        >
          <p className="text-sm text-fg-subtle">
            © {year} {tSite("name")}. {t("rights")}
          </p>

          <Link
            href="/accessibility"
            className="
              inline-flex min-h-[var(--tap-target-min)] items-center
              text-sm text-fg-muted underline underline-offset-4
              transition-colors duration-[var(--duration-fast)]
              hover:text-brand
            "
          >
            {t("accessibilityStatement")}
          </Link>
        </div>
      </Container>
    </footer>
  );
}
