// src/components/layout/MiniMascot.tsx
"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useTranslations } from "next-intl";
import { XIcon, SparklesIcon } from "lucide-react";
import { useSettingsStore, selectReducedMotion } from "@/stores/settings-store";
import { useHydrated } from "@/hooks/use-hydrated";
import { cn } from "@/lib/utils/cn";

/**
 * Mini-personaj (TZ 12.2) — sof dekorativ element.
 *
 *  - Ekran burchagida qat'iy pozitsiya, kontent/tugmalarni to'smaydi.
 *  - Desktop: kursor tomon «qaraydi» (ko'z qorachig'i harakati).
 *  - Planshet/telefon: teginishda qisqa sakrash reaksiyasi.
 *  - Yig'ilishi mumkin; holat localStorage'da (`si:mascot`) saqlanadi.
 *  - Biznes-mantiqsiz: syujet/holat yo'q.
 *  - `reducedMotion` yoqilganda idle animatsiya o'chadi.
 */

const STORAGE_KEY = "si:mascot";

export function MiniMascot() {
  const t = useTranslations("mascot");
  const hydrated = useHydrated();
  const reducedMotion = useSettingsStore(selectReducedMotion);
  const prefersReduced = reducedMotion === true;

  const [collapsed, setCollapsed] = useState(false);
  const [pupil, setPupil] = useState({ x: 0, y: 0 });
  const [reacting, setReacting] = useState(false);
  const rootRef = useRef<HTMLDivElement | null>(null);
  const reactTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // localStorage'dan yig'ilgan holatni o'qish.
  useEffect(() => {
    try {
      setCollapsed(localStorage.getItem(STORAGE_KEY) === "1");
    } catch {}
  }, []);

  const persistCollapsed = useCallback((value: boolean) => {
    setCollapsed(value);
    try {
      localStorage.setItem(STORAGE_KEY, value ? "1" : "0");
    } catch {}
  }, []);

  // Kursorga qarash (faqat kengaytirilgan ko'rinishda).
  useEffect(() => {
    if (collapsed) return;
    const onMove = (e: MouseEvent) => {
      const el = rootRef.current;
      if (!el) return;
      const rect = el.getBoundingClientRect();
      const cx = rect.left + rect.width / 2;
      const cy = rect.top + rect.height / 2;
      const angle = Math.atan2(e.clientY - cy, e.clientX - cx);
      const dist = 3; // qorachiq siljishi (px)
      setPupil({ x: Math.cos(angle) * dist, y: Math.sin(angle) * dist });
    };
    window.addEventListener("mousemove", onMove);
    return () => window.removeEventListener("mousemove", onMove);
  }, [collapsed]);

  useEffect(() => {
    return () => {
      if (reactTimer.current) clearTimeout(reactTimer.current);
    };
  }, []);

  const triggerReaction = useCallback(() => {
    setReacting(true);
    if (reactTimer.current) clearTimeout(reactTimer.current);
    reactTimer.current = setTimeout(() => setReacting(false), 600);
  }, []);

  // SSR'da render qilmaymiz — localStorage holatiga bog'liq.
  if (!hydrated) return null;

  if (collapsed) {
    return (
      <button
        type="button"
        onClick={() => persistCollapsed(false)}
        className={cn(
          "fixed bottom-4 right-4 z-[var(--z-header)] flex h-11 w-11 items-center justify-center rounded-full",
          "border border-border bg-surface text-brand shadow-lg transition-transform hover:scale-105 active:scale-95",
          "focus-visible:outline-3 focus-visible:outline-[var(--focus-ring)]",
        )}
        aria-label={t("show")}
      >
        <SparklesIcon className="h-5 w-5" />
      </button>
    );
  }

  return (
    <div
      ref={rootRef}
      className="fixed bottom-4 right-4 z-[var(--z-header)] select-none"
      aria-hidden="true"
    >
      <div className="relative">
        {/* Yig'ish tugmasi */}
        <button
          type="button"
          onClick={() => persistCollapsed(true)}
          className={cn(
            "absolute -top-1 -right-1 z-10 flex h-6 w-6 items-center justify-center rounded-full",
            "border border-border bg-surface text-fg-muted shadow-sm transition-colors hover:text-fg hover:bg-surface-muted",
            "focus-visible:outline-2 focus-visible:outline-[var(--focus-ring)]",
          )}
          aria-label={t("hide")}
        >
          <XIcon className="h-3.5 w-3.5" />
        </button>

        {/* Personaj */}
        <button
          type="button"
          onClick={triggerReaction}
          className={cn(
            "block rounded-full focus-visible:outline-3 focus-visible:outline-[var(--focus-ring)]",
            !prefersReduced && "animate-mascot-idle",
            reacting && "animate-mascot-pop",
          )}
        >
          <svg
            width="72"
            height="72"
            viewBox="0 0 72 72"
            className="drop-shadow-lg"
            role="img"
          >
            {/* Tana */}
            <circle cx="36" cy="36" r="30" className="fill-brand" />
            <circle cx="36" cy="36" r="30" className="fill-none stroke-brand-hover" strokeWidth="2" />
            {/* Yuz */}
            <circle cx="36" cy="34" r="20" className="fill-surface" />
            {/* Ko'zlar (oq) */}
            <circle cx="29" cy="32" r="5" className="fill-white stroke-border" strokeWidth="0.5" />
            <circle cx="43" cy="32" r="5" className="fill-white stroke-border" strokeWidth="0.5" />
            {/* Qorachiqlar — kursorga ergashadi */}
            <circle cx={29 + pupil.x} cy={32 + pupil.y} r="2.4" className="fill-fg" />
            <circle cx={43 + pupil.x} cy={32 + pupil.y} r="2.4" className="fill-fg" />
            {/* Tabassum */}
            <path
              d="M28 42 Q36 49 44 42"
              className="fill-none stroke-brand"
              strokeWidth="2.5"
              strokeLinecap="round"
            />
            {/* Yonoqlar */}
            <circle cx="24" cy="40" r="2.5" className="fill-accent/40" />
            <circle cx="48" cy="40" r="2.5" className="fill-accent/40" />
          </svg>
        </button>
      </div>

      <style>{`
        @keyframes mascotIdle {
          0%, 100% { transform: translateY(0) rotate(0deg); }
          50% { transform: translateY(-6px) rotate(-2deg); }
        }
        @keyframes mascotPop {
          0% { transform: scale(1); }
          40% { transform: scale(1.15) rotate(6deg); }
          100% { transform: scale(1) rotate(0deg); }
        }
        .animate-mascot-idle { animation: mascotIdle 3.2s ease-in-out infinite; }
        .animate-mascot-pop { animation: mascotPop 0.6s cubic-bezier(0.34, 1.56, 0.64, 1); }
      `}</style>
    </div>
  );
}

// src/components/layout/MiniMascot.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { X } from '@lucide/vue'
import { useSettingsStore } from '@/stores/useSettingsStore'
import { isMascotCollapsed, setMascotCollapsed } from '@/lib/storage/progress'

/**
 * Mini-personaj (TZ 12.2) — SOF DEKORATIV.
 *
 * Syujeti, replikasi va bo'limlarga bog'liq holati yo'q: kursorga "qaraydi",
 * teginilganda qisqa reaksiya beradi, xolos. Biznes-mantiqqa aralashmaydi.
 *
 * Kontent va tugmalarni to'smasligi shart, shuning uchun burchakda va
 * `pointer-events` faqat o'zida.
 */
const { t } = useI18n()
const settings = useSettingsStore()

const collapsed = ref(isMascotCollapsed())
const pupil = ref({ x: 0, y: 0 })
const reacting = ref(false)
const root = ref<HTMLElement | null>(null)
let reactTimer: ReturnType<typeof setTimeout> | undefined

/** Harakat kamaytirilganda ko'z ham, reaksiya ham qotib turadi. */
const isStill = computed(() => settings.reducedMotion === true)

function onPointerMove(event: PointerEvent) {
  if (!root.value || isStill.value) return
  const r = root.value.getBoundingClientRect()
  const cx = r.left + r.width / 2
  const cy = r.top + r.height / 2
  const dx = event.clientX - cx
  const dy = event.clientY - cy
  const dist = Math.hypot(dx, dy) || 1
  // Qorachiq ko'z ichida qoladi — 3px dan chiqmaydi.
  const limit = Math.min(3, dist / 40)
  pupil.value = { x: (dx / dist) * limit, y: (dy / dist) * limit }
}

function react() {
  if (isStill.value) return
  reacting.value = true
  clearTimeout(reactTimer)
  reactTimer = setTimeout(() => (reacting.value = false), 600)
}

function collapse() {
  collapsed.value = true
  setMascotCollapsed(true)
}

function expand() {
  collapsed.value = false
  setMascotCollapsed(false)
}

onMounted(() => window.addEventListener('pointermove', onPointerMove, { passive: true }))
onBeforeUnmount(() => {
  window.removeEventListener('pointermove', onPointerMove)
  clearTimeout(reactTimer)
})
</script>

<template>
  <!-- Yig'ilgan holat: kichkina qayta ochish tugmasi -->
  <button
    v-if="collapsed"
    type="button"
    class="fixed bottom-4 right-4 z-40 w-11 h-11 rounded-full bg-[var(--brand)] text-[var(--fg-on-brand)] shadow-[var(--si-shadow-lg)] flex items-center justify-center text-lg font-black cursor-pointer hover:scale-105 transition-transform"
    :aria-label="t('mascot.expand')"
    @click="expand"
  >
    ◕
  </button>

  <div
    v-else
    ref="root"
    class="fixed bottom-4 right-4 z-40 select-none"
    :aria-label="t('mascot.label')"
    role="img"
  >
    <button
      type="button"
      class="absolute -top-2 -left-2 w-6 h-6 rounded-full bg-[var(--surface)] border border-[var(--border-default)] text-[var(--fg-muted)] flex items-center justify-center cursor-pointer hover:text-[var(--fg)] transition-colors"
      :aria-label="t('mascot.collapse')"
      @click="collapse"
    >
      <X class="w-3.5 h-3.5" aria-hidden="true" />
    </button>

    <div
      class="w-16 h-16 rounded-full bg-gradient-to-br from-[var(--brand)] to-[var(--brand-hover)] shadow-[var(--si-shadow-lg)] flex items-center justify-center gap-1.5 cursor-pointer"
      :class="{ 'mascot-idle': !isStill, 'mascot-react': reacting }"
      @click="react"
      @touchstart.passive="react"
    >
      <span
        v-for="side in ['l', 'r']"
        :key="side"
        class="w-4 h-4 rounded-full bg-white flex items-center justify-center"
      >
        <span
          class="w-1.5 h-1.5 rounded-full bg-slate-900 transition-transform duration-75"
          :style="{ transform: `translate(${pupil.x}px, ${pupil.y}px)` }"
        />
      </span>
    </div>
  </div>
</template>

<style scoped>
.mascot-idle {
  animation: bob 3.2s ease-in-out infinite;
}

.mascot-react {
  animation: pop 0.6s ease-out;
}

@keyframes bob {
  0%,
  100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-5px);
  }
}

@keyframes pop {
  0% {
    transform: scale(1);
  }
  35% {
    transform: scale(1.18) rotate(-6deg);
  }
  100% {
    transform: scale(1);
  }
}
</style>
