// src/components/layout/SkipLink.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n'

/**
 * Klaviatura foydalanuvchilari uchun navigatsiyani o'tkazib yuborish havolasi
 * (WCAG 2.4.1). Odatda ko'rinmaydi — faqat fokus olganda chiqadi.
 */
const { t } = useI18n()
</script>

<template>
  <a
    href="#main-content"
    class="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[var(--z-skip-link)] focus:px-5 focus:py-3 focus:rounded-xl focus:bg-[var(--brand)] focus:text-[var(--fg-on-brand)] focus:font-bold focus:shadow-xl"
  >
    {{ t('a11y.skipToContent') }}
  </a>
</template>

// src/components/layout/SkipLink.tsx
"use client";

import { useTranslations } from "next-intl";

/** Asosiy kontent maydonining id'si — `SkipLink` shu yerga sakraydi. */
export const MAIN_CONTENT_ID = "main-content";

/**
 * "Asosiy kontentga o'tish" havolasi.
 *
 * WCAG 2.4.1 (Bypass Blocks). Klaviatura va ekran o'quvchi foydalanuvchisi
 * har bir sahifada 20+ navigatsiya havolasini bosib o'tmasligi uchun.
 *
 * Odatda ko'rinmaydi; faqat Tab bosilganda birinchi element sifatida chiqadi.
 * Shuning uchun `sr-only` emas — fokusga kelganda KO'RINISHI shart.
 */
export function SkipLink() {
  const t = useTranslations("a11y");

  return (
    <a
      href={`#${MAIN_CONTENT_ID}`}
      className="
        absolute left-4 top-4 z-[var(--z-skip-link)]
        -translate-y-[200%] focus:translate-y-0
        rounded-md bg-brand px-5 py-3 text-base font-medium text-fg-on-brand
        shadow-lg transition-transform duration-[var(--duration-fast)]
      "
    >
      {t("skipToContent")}
    </a>
  );
}
