// src/components/settings/AccessibilityPanel.tsx
"use client";

import { useState, useRef, useId } from "react";
import { createPortal } from "react-dom";
import { useTranslations } from "next-intl";
import { 
  PersonStanding, 
  SunIcon, 
  MoonIcon, 
  EyeIcon, 
  PaletteIcon, 
  HelpCircleIcon,
  XIcon,
  MinusIcon,
  PlusIcon
} from "lucide-react";
import { useSettingsStore } from "@/stores/settings-store";
import { useSettingsHydrated } from "@/hooks/use-hydrated";
import { FONT_SCALES, type FontScale } from "@/types/settings";
import { useFocusTrap } from "@/hooks/use-focus-trap";
import { useBodyScrollLock } from "@/hooks/use-body-scroll-lock";
import { cn } from "@/lib/utils/cn";

interface AccessibilityPanelProps {
  /** `compact` — headerda ikonka; `list` — drawer/sozlamalarda matn bilan. */
  variant?: "compact" | "list";
  className?: string;
}

export function AccessibilityPanel({ variant = "compact", className }: AccessibilityPanelProps) {
  const t = useTranslations("a11y");
  const tc = useTranslations("common");
  const hydrated = useSettingsHydrated();
  const [isOpen, setIsOpen] = useState(false);
  const drawerRef = useRef<HTMLDivElement>(null);
  const titleId = useId();

  const theme = useSettingsStore((s) => s.theme);
  const fontScale = useSettingsStore((s) => s.fontScale);
  const reducedMotion = useSettingsStore((s) => s.reducedMotion);
  const dyslexicFont = useSettingsStore((s) => s.dyslexicFont);

  const setTheme = useSettingsStore((s) => s.setTheme);
  const setFontScale = useSettingsStore((s) => s.setFontScale);
  const setReducedMotion = useSettingsStore((s) => s.setReducedMotion);
  const setDyslexicFont = useSettingsStore((s) => s.setDyslexicFont);
  const reset = useSettingsStore((s) => s.reset);

  const currentIndex = FONT_SCALES.indexOf(fontScale);
  const canDecrease = currentIndex > 0;
  const canIncrease = currentIndex !== -1 && currentIndex < FONT_SCALES.length - 1;

  const handleDecreaseFont = () => {
    if (canDecrease) {
      setFontScale(FONT_SCALES[currentIndex - 1]!);
    }
  };

  const handleIncreaseFont = () => {
    if (canIncrease) {
      setFontScale(FONT_SCALES[currentIndex + 1]!);
    }
  };

  const isList = variant === "list";

  const handleOpen = () => setIsOpen(true);
  const handleClose = () => setIsOpen(false);

  // Focus trap inside the drawer
  useFocusTrap(isOpen, drawerRef, handleClose);
  
  // Body scroll lock when open
  useBodyScrollLock(isOpen);

  // Portal target in browser body
  const drawerPortal = typeof document !== "undefined" ? document.body : null;

  return (
    <>
      <button
        type="button"
        onClick={handleOpen}
        disabled={!hydrated}
        aria-haspopup="dialog"
        aria-expanded={isOpen}
        aria-label={t("accessibilitySettings")}
        title={t("accessibilitySettings")}
        className={cn(
          "flex items-center rounded-lg text-fg focus-visible:ring-2 focus-visible:ring-focus",
          "transition-colors duration-[var(--duration-fast)]",
          "hover:bg-surface-muted disabled:opacity-60",
          isList
            ? "w-full min-h-[var(--tap-target-min)] gap-3 px-4 text-base font-medium"
            : "tap-target justify-center",
          className
        )}
      >
        <PersonStanding className="h-6 w-6 shrink-0" aria-hidden="true" />
        {isList && <span>{t("accessibilitySettings")}</span>}
      </button>

      {isOpen && hydrated && drawerPortal && createPortal(
        <div className="fixed inset-0 z-[var(--z-overlay)] flex justify-end">
          {/* Backdrop (Dark overlay behind drawer) */}
          <div
            className="fixed inset-0 bg-overlay animate-in fade-in duration-[var(--duration-base)]"
            aria-hidden="true"
            onClick={handleClose}
          />

          {/* Drawer Panel - Wide side drawer with big accessible padding and child-friendly design */}
          <div
            ref={drawerRef}
            role="dialog"
            aria-modal="true"
            aria-labelledby={titleId}
            className={cn(
              "relative z-[var(--z-drawer)] h-full w-[min(34rem,95vw)] flex flex-col bg-surface border-l border-border p-5 md:p-6 shadow-xl",
              "animate-in slide-in-from-right duration-[var(--duration-slow)] ease-out"
            )}
          >
            {/* Header with Close Button */}
            <div className="flex items-center justify-between mb-4 border-b border-border/50 pb-3">
              <h2 id={titleId} className="text-lg md:text-xl font-black text-fg font-display">
                {t("accessibilitySettings")}
              </h2>

              <button
                type="button"
                onClick={handleClose}
                className={cn(
                  "tap-target flex items-center justify-center rounded-lg text-fg-muted",
                  "transition-colors duration-[var(--duration-fast)]",
                  "hover:bg-surface-muted hover:text-fg",
                  "focus-visible:outline-3 focus-visible:outline-[var(--focus-ring)]"
                )}
              >
                <XIcon className="h-6 w-6" aria-hidden="true" />
                <span className="sr-only">{tc("close")}</span>
              </button>
            </div>

            {/* Scrollable controls container */}
            <div className="flex-1 flex flex-col justify-between overflow-y-auto overflow-x-hidden px-1 py-1 gap-4 w-full">
              
              {/* --- 1. MAVZULAR (Themes) - Big Tap Targets for Children --- */}
              <div className="space-y-2">
                <h3 className="text-xs font-bold text-fg-muted uppercase tracking-wider flex items-center gap-2">
                  <PaletteIcon className="h-3.5 w-3.5 text-brand" aria-hidden="true" />
                  {t("theme")}
                </h3>
                <div className="grid grid-cols-2 gap-2">
                  {/* Light */}
                  <button
                    type="button"
                    onClick={() => setTheme("light")}
                    className={cn(
                      "flex items-center justify-center gap-2.5 px-3 py-2.5 rounded-xl border-2 text-sm font-bold transition-all duration-[var(--duration-fast)]",
                      theme === "light"
                        ? "border-brand bg-brand-subtle text-brand ring-2 ring-brand/35"
                        : "border-border hover:bg-surface-muted text-fg"
                    )}
                  >
                    <SunIcon className="h-4.5 w-4.5" aria-hidden="true" />
                    <span>{t("themeLight")}</span>
                  </button>

                  {/* Dark */}
                  <button
                    type="button"
                    onClick={() => setTheme("dark")}
                    className={cn(
                      "flex items-center justify-center gap-2.5 px-3 py-2.5 rounded-xl border-2 text-sm font-bold transition-all duration-[var(--duration-fast)]",
                      theme === "dark"
                        ? "border-brand bg-brand-subtle text-brand ring-2 ring-brand/35"
                        : "border-border hover:bg-surface-muted text-fg"
                    )}
                  >
                    <MoonIcon className="h-4.5 w-4.5" aria-hidden="true" />
                    <span>{t("themeDark")}</span>
                  </button>

                  {/* High Contrast */}
                  <button
                    type="button"
                    onClick={() => setTheme("high-contrast")}
                    className={cn(
                      "flex items-center justify-center gap-2.5 px-3 py-2.5 rounded-xl border-2 text-sm font-bold transition-all duration-[var(--duration-fast)]",
                      theme === "high-contrast"
                        ? "border-brand bg-brand-subtle text-brand ring-2 ring-brand/35"
                        : "border-border hover:bg-surface-muted text-fg"
                    )}
                  >
                    <EyeIcon className="h-4.5 w-4.5" aria-hidden="true" />
                    <span>{t("themeHighContrast")}</span>
                  </button>

                  {/* Monochrome */}
                  <button
                    type="button"
                    onClick={() => setTheme("monochrome")}
                    className={cn(
                      "flex items-center justify-center gap-2.5 px-3 py-2.5 rounded-xl border-2 text-sm font-bold transition-all duration-[var(--duration-fast)]",
                      theme === "monochrome"
                        ? "border-brand bg-brand-subtle text-brand ring-2 ring-brand/35"
                        : "border-border hover:bg-surface-muted text-fg"
                    )}
                  >
                    <PaletteIcon className="h-4.5 w-4.5" aria-hidden="true" />
                    <span>{t("themeMonochrome")}</span>
                  </button>
                </div>
              </div>

              {/* --- 2. MATN O'LCHAMI (Font Scale) - Spaced and Wide Grid --- */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-xs font-bold text-fg-muted uppercase tracking-wider flex items-center gap-1.5">
                    <span className="text-lg font-black leading-none">A</span>
                    <span>{t("fontScale")}</span>
                  </h3>
                  <span className="text-base font-black text-brand">
                    {Math.round(fontScale * 100)}%
                  </span>
                </div>

                <div className="flex items-center justify-between gap-3 bg-surface-muted p-2 rounded-xl border border-border/40 w-full">
                  <button
                    type="button"
                    onClick={handleDecreaseFont}
                    disabled={!canDecrease}
                    aria-label="Matn o'lchamini kichiklashtirish"
                    className={cn(
                      "tap-target w-10 h-10 rounded-lg bg-surface border border-border flex items-center justify-center font-bold text-lg text-fg transition-all duration-[var(--duration-fast)]",
                      "hover:bg-brand-subtle hover:text-brand disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-surface disabled:hover:text-fg",
                      "focus-visible:outline-3 focus-visible:outline-[var(--focus-ring)]"
                    )}
                  >
                    <MinusIcon className="h-4 w-4" aria-hidden="true" />
                  </button>
                  
                  {/* Visual slider progress bar */}
                  <div className="flex-1 px-3 flex items-center justify-between gap-1 select-none">
                    {FONT_SCALES.map((scale, i) => (
                      <div
                        key={scale}
                        className={cn(
                          "h-2.5 rounded-full flex-1 transition-all duration-[var(--duration-fast)]",
                          i <= currentIndex ? "bg-brand" : "bg-border-strong/60"
                        )}
                      />
                    ))}
                  </div>

                  <button
                    type="button"
                    onClick={handleIncreaseFont}
                    disabled={!canIncrease}
                    aria-label="Matn o'lchamini kattalashtirish"
                    className={cn(
                      "tap-target w-10 h-10 rounded-lg bg-surface border border-border flex items-center justify-center font-bold text-lg text-fg transition-all duration-[var(--duration-fast)]",
                      "hover:bg-brand-subtle hover:text-brand disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:bg-surface disabled:hover:text-fg",
                      "focus-visible:outline-3 focus-visible:outline-[var(--focus-ring)]"
                    )}
                  >
                    <PlusIcon className="h-4 w-4" aria-hidden="true" />
                  </button>
                </div>
              </div>

              {/* --- 3 & 4. DYSLEXIA & REDUCED MOTION TOGGLES (Vertical Stack) --- */}
              <div className="flex flex-col gap-2.5 border-t border-border/50 pt-4">
                {/* Dyslexia Mode */}
                <div className="flex items-center justify-between p-3 rounded-2xl bg-surface-muted border border-border/40 gap-4">
                  <div className="space-y-0.5">
                    <label htmlFor="dyslexia-toggle-drawer" className="text-sm font-bold text-fg block select-none">
                      {t("dyslexiaMode")}
                    </label>
                    <span className="text-[10px] text-fg-muted leading-tight block">
                      Disleksiyali bolalar uchun maxsus qulay shrift.
                    </span>
                  </div>
                  <button
                    id="dyslexia-toggle-drawer"
                    type="button"
                    role="switch"
                    aria-checked={dyslexicFont}
                    onClick={() => setDyslexicFont(!dyslexicFont)}
                    className={cn(
                      "relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-brand",
                      dyslexicFont ? "bg-brand" : "bg-border-strong"
                    )}
                  >
                    <span
                      aria-hidden="true"
                      className={cn(
                        "pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out",
                        dyslexicFont ? "translate-x-5" : "translate-x-0"
                      )}
                    />
                  </button>
                </div>

                {/* Reduced Motion */}
                <div className="flex items-center justify-between p-3 rounded-2xl bg-surface-muted border border-border/40 gap-4">
                  <div className="space-y-0.5">
                    <label htmlFor="motion-toggle-drawer" className="text-sm font-bold text-fg block select-none">
                      {t("reducedMotion")}
                    </label>
                    <span className="text-[10px] text-fg-muted leading-tight block">
                      Tezkor animatsiyalar va harakatlarni kamaytiradi.
                    </span>
                  </div>
                  <button
                    id="motion-toggle-drawer"
                    type="button"
                    role="switch"
                    aria-checked={!!reducedMotion}
                    onClick={() => setReducedMotion(reducedMotion ? null : true)}
                    className={cn(
                      "relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-brand",
                      reducedMotion ? "bg-brand" : "bg-border-strong"
                    )}
                  >
                    <span
                      aria-hidden="true"
                      className={cn(
                        "pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out",
                        reducedMotion ? "translate-x-5" : "translate-x-0"
                      )}
                    />
                  </button>
                </div>
              </div>

              {/* --- 5. BEKOR QILISH (RESET) TUGMASI --- */}
              <div className="pt-2 border-t border-border/50">
                <button
                  type="button"
                  onClick={reset}
                  className="w-full flex items-center justify-center min-h-[var(--tap-target-min)] bg-surface-muted text-fg hover:bg-surface-muted/80 font-bold text-sm rounded-xl transition-all duration-[var(--duration-fast)] focus-visible:ring-2 focus-visible:ring-focus"
                >
                  {t("resetSettings")}
                </button>
              </div>
            </div>
      </div>
    </div>,
    drawerPortal
  )}
    </>
  );
}

// src/components/settings/AccessibilityPanel.vue
<script setup lang="ts">
import { computed, ref, useId } from 'vue'
import { useI18n } from 'vue-i18n'
import { PersonStanding, Sun, Moon, Eye, Palette, X, Minus, Plus } from '@lucide/vue'
import { useSettingsStore } from '@/stores/useSettingsStore'
import { useModalBehavior } from '@/composables/useModalBehavior'
import { FONT_SCALES, type FontScale, type ThemeMode } from '@/types/settings'

withDefaults(
  defineProps<{
    /** `compact` — headerda ikonka; `list` — mobil menyuda matn bilan. */
    variant?: 'compact' | 'list'
  }>(),
  { variant: 'compact' },
)

const { t } = useI18n()
const settings = useSettingsStore()

const isOpen = ref(false)
const panelRef = ref<HTMLElement | null>(null)
const titleId = useId()

useModalBehavior(isOpen, panelRef, () => (isOpen.value = false))

const themeOptions: { value: ThemeMode; icon: typeof Sun; labelKey: string }[] = [
  { value: 'light', icon: Sun, labelKey: 'a11y.themeLight' },
  { value: 'dark', icon: Moon, labelKey: 'a11y.themeDark' },
  { value: 'high-contrast', icon: Eye, labelKey: 'a11y.themeHighContrast' },
  { value: 'monochrome', icon: Palette, labelKey: 'a11y.themeMonochrome' },
]

const currentIndex = computed(() => FONT_SCALES.indexOf(settings.fontScale))
const canDecrease = computed(() => currentIndex.value > 0)
const canIncrease = computed(
  () => currentIndex.value !== -1 && currentIndex.value < FONT_SCALES.length - 1,
)

function stepFont(delta: -1 | 1) {
  const next = FONT_SCALES[currentIndex.value + delta] as FontScale | undefined
  if (next !== undefined) settings.fontScale = next
}
</script>

<template>
  <button
    type="button"
    aria-haspopup="dialog"
    :aria-expanded="isOpen"
    :aria-label="t('a11y.accessibilitySettings')"
    :title="t('a11y.accessibilitySettings')"
    class="flex items-center rounded-lg text-[var(--fg)] transition-colors hover:bg-[var(--surface-muted)]"
    :class="variant === 'list' ? 'w-full min-h-[var(--tap-target-min)] gap-3 px-4 text-base font-medium' : 'tap-target justify-center'"
    @click="isOpen = true"
  >
    <PersonStanding class="h-6 w-6 shrink-0" aria-hidden="true" />
    <span v-if="variant === 'list'">{{ t('a11y.accessibilitySettings') }}</span>
  </button>

  <Teleport to="body">
    <div v-if="isOpen" class="fixed inset-0 z-[var(--z-overlay)] flex justify-end">
      <div
        class="fixed inset-0 bg-[var(--overlay)] animate-in fade-in duration-200"
        aria-hidden="true"
        @click="isOpen = false"
      />

      <div
        ref="panelRef"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="titleId"
        class="relative z-[var(--z-drawer)] h-full w-[min(34rem,95vw)] flex flex-col bg-[var(--surface)] border-l border-[var(--border-default)] p-5 md:p-6 shadow-[var(--si-shadow-lg)] animate-in slide-in-from-right duration-300 ease-out"
      >
        <div
          class="flex items-center justify-between mb-4 border-b border-[var(--border-default)] pb-3"
        >
          <h2 :id="titleId" class="text-lg md:text-xl font-black text-[var(--fg)] font-display">
            {{ t('a11y.accessibilitySettings') }}
          </h2>
          <button
            type="button"
            class="tap-target flex items-center justify-center rounded-lg text-[var(--fg-muted)] transition-colors hover:bg-[var(--surface-muted)] hover:text-[var(--fg)]"
            @click="isOpen = false"
          >
            <X class="h-6 w-6" aria-hidden="true" />
            <span class="sr-only">{{ t('common.close') }}</span>
          </button>
        </div>

        <div class="flex-1 flex flex-col overflow-y-auto overflow-x-hidden px-1 py-1 gap-4 w-full">
          <!-- 1. Mavzular -->
          <div class="space-y-2">
            <h3
              class="text-xs font-bold text-[var(--fg-muted)] uppercase tracking-wider flex items-center gap-2"
            >
              <Palette class="h-3.5 w-3.5 text-[var(--brand)]" aria-hidden="true" />
              {{ t('a11y.theme') }}
            </h3>
            <div class="grid grid-cols-2 gap-2">
              <button
                v-for="opt in themeOptions"
                :key="opt.value"
                type="button"
                :aria-pressed="settings.theme === opt.value"
                class="flex items-center justify-center gap-2.5 px-3 py-2.5 rounded-xl border-2 text-sm font-bold transition-all"
                :class="settings.theme === opt.value ? 'border-[var(--brand)] bg-[var(--brand-subtle)] text-[var(--brand)]' : 'border-[var(--border-default)] text-[var(--fg)] hover:bg-[var(--surface-muted)]'"
                @click="settings.theme = opt.value"
              >
                <component :is="opt.icon" class="h-4 w-4" aria-hidden="true" />
                <span>{{ t(opt.labelKey) }}</span>
              </button>
            </div>
          </div>

          <!-- 2. Matn o'lchami -->
          <div class="space-y-2">
            <div class="flex items-center justify-between">
              <h3
                class="text-xs font-bold text-[var(--fg-muted)] uppercase tracking-wider flex items-center gap-1.5"
              >
                <span class="text-lg font-black leading-none">A</span>
                <span>{{ t('a11y.fontScale') }}</span>
              </h3>
              <span class="text-base font-black text-[var(--brand)]">
                {{ Math.round(settings.fontScale * 100) }}%
              </span>
            </div>

            <div
              class="flex items-center justify-between gap-3 bg-[var(--surface-muted)] p-2 rounded-xl border border-[var(--border-default)] w-full"
            >
              <button
                type="button"
                :disabled="!canDecrease"
                aria-label="Matn o'lchamini kichiklashtirish"
                class="tap-target w-10 h-10 rounded-lg bg-[var(--surface)] border border-[var(--border-default)] flex items-center justify-center text-[var(--fg)] transition-all hover:bg-[var(--brand-subtle)] hover:text-[var(--brand)] disabled:opacity-40 disabled:cursor-not-allowed"
                @click="stepFont(-1)"
              >
                <Minus class="h-4 w-4" aria-hidden="true" />
              </button>

              <div class="flex-1 px-3 flex items-center justify-between gap-1 select-none">
                <div
                  v-for="(scale, i) in FONT_SCALES"
                  :key="scale"
                  class="h-2.5 rounded-full flex-1 transition-all"
                  :class="i <= currentIndex ? 'bg-[var(--brand)]' : 'bg-[var(--border-strong)]'"
                />
              </div>

              <button
                type="button"
                :disabled="!canIncrease"
                aria-label="Matn o'lchamini kattalashtirish"
                class="tap-target w-10 h-10 rounded-lg bg-[var(--surface)] border border-[var(--border-default)] flex items-center justify-center text-[var(--fg)] transition-all hover:bg-[var(--brand-subtle)] hover:text-[var(--brand)] disabled:opacity-40 disabled:cursor-not-allowed"
                @click="stepFont(1)"
              >
                <Plus class="h-4 w-4" aria-hidden="true" />
              </button>
            </div>
          </div>

          <!-- 3 & 4. Disleksiya va harakat -->
          <div class="flex flex-col gap-2.5 border-t border-[var(--border-default)] pt-4">
            <div
              class="flex items-center justify-between p-3 rounded-2xl bg-[var(--surface-muted)] border border-[var(--border-default)] gap-4"
            >
              <div class="space-y-0.5">
                <span class="text-sm font-bold text-[var(--fg)] block select-none">
                  {{ t('a11y.dyslexiaMode') }}
                </span>
                <span class="text-[10px] text-[var(--fg-muted)] leading-tight block">
                  Disleksiyali bolalar uchun maxsus qulay shrift.
                </span>
              </div>
              <button
                type="button"
                role="switch"
                :aria-checked="settings.dyslexicFont"
                :aria-label="t('a11y.dyslexiaMode')"
                class="relative inline-flex h-6 w-11 shrink-0 rounded-full border-2 border-transparent transition-colors"
                :class="settings.dyslexicFont ? 'bg-[var(--brand)]' : 'bg-[var(--border-strong)]'"
                @click="settings.dyslexicFont = !settings.dyslexicFont"
              >
                <span
                  aria-hidden="true"
                  class="pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow transition"
                  :class="settings.dyslexicFont ? 'translate-x-5' : 'translate-x-0'"
                />
              </button>
            </div>

            <div
              class="flex items-center justify-between p-3 rounded-2xl bg-[var(--surface-muted)] border border-[var(--border-default)] gap-4"
            >
              <div class="space-y-0.5">
                <span class="text-sm font-bold text-[var(--fg)] block select-none">
                  {{ t('a11y.reducedMotion') }}
                </span>
                <span class="text-[10px] text-[var(--fg-muted)] leading-tight block">
                  Tezkor animatsiyalar va harakatlarni kamaytiradi.
                </span>
              </div>
              <button
                type="button"
                role="switch"
                :aria-checked="settings.reducedMotion === true"
                :aria-label="t('a11y.reducedMotion')"
                class="relative inline-flex h-6 w-11 shrink-0 rounded-full border-2 border-transparent transition-colors"
                :class="settings.reducedMotion ? 'bg-[var(--brand)]' : 'bg-[var(--border-strong)]'"
                @click="settings.reducedMotion = settings.reducedMotion ? null : true"
              >
                <span
                  aria-hidden="true"
                  class="pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow transition"
                  :class="settings.reducedMotion ? 'translate-x-5' : 'translate-x-0'"
                />
              </button>
            </div>
          </div>

          <!-- 5. Bekor qilish -->
          <div class="pt-2 mt-auto border-t border-[var(--border-default)]">
            <button
              type="button"
              class="w-full flex items-center justify-center min-h-[var(--tap-target-min)] bg-[var(--surface-muted)] text-[var(--fg)] hover:opacity-80 font-bold text-sm rounded-xl transition-all"
              @click="settings.reset()"
            >
              {{ t('a11y.resetSettings') }}
            </button>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>
