// src/components/ui/SlideWizard.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useTranslations } from "next-intl";
import { ChevronLeftIcon, ChevronRightIcon, XIcon, CheckIcon, RotateCcwIcon, ArrowLeftIcon } from "lucide-react";
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { EmptyState } from "@/components/ui/EmptyState";
import { cn } from "@/lib/utils/cn";

export interface SlideItem {
  id: string;
  title: string;
  description: string;
  imageUrl?: string;
}

interface SlideWizardProps {
  title: string;
  slides: SlideItem[];
  onClose: () => void;
  onComplete?: () => void; // Optional global callback on finish click
  completionTitle?: string;
  completionDescription?: string;
  completionAction?: React.ReactNode;
}

export function SlideWizard({
  title,
  slides,
  onClose,
  onComplete,
  completionTitle,
  completionDescription,
  completionAction,
}: SlideWizardProps) {
  const t = useTranslations("slides");
  const [currentIdx, setCurrentIdx] = useState(0);
  const [showCompletion, setShowCompletion] = useState(false);

  const totalSlides = slides.length;

  // Keyboard navigation hook - must be declared before early returns
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (document.activeElement?.tagName === "INPUT" || document.activeElement?.tagName === "TEXTAREA") {
        return;
      }

      if (e.key === "ArrowRight") {
        if (currentIdx < totalSlides - 1) {
          e.preventDefault();
          setCurrentIdx((idx) => idx + 1);
        } else if (!showCompletion) {
          e.preventDefault();
          onComplete?.();
          setShowCompletion(true);
        }
      } else if (e.key === "ArrowLeft") {
        if (currentIdx > 0 && !showCompletion) {
          e.preventDefault();
          setCurrentIdx((idx) => idx - 1);
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [currentIdx, totalSlides, showCompletion, onComplete]);
  
  // Safe bounds check
  if (totalSlides === 0) {
    return (
      <Card className="p-8 text-center border border-border">
        <p className="text-fg-muted">{t("noSlides")}</p>
        <Button onClick={onClose} className="mt-4">{t("back")}</Button>
      </Card>
    );
  }

  const currentSlide = slides[currentIdx]!;

  const handlePrev = () => {
    if (currentIdx > 0) {
      setCurrentIdx((i) => i - 1);
    }
  };

  const handleNext = () => {
    if (currentIdx < totalSlides - 1) {
      setCurrentIdx((i) => i + 1);
    } else {
      onComplete?.();
      setShowCompletion(true);
    }
  };

  const handleRestart = () => {
    setCurrentIdx(0);
    setShowCompletion(false);
  };

  // COMPLETION VIEW
  if (showCompletion) {
    return (
      <div className="max-w-2xl mx-auto rounded-2xl border border-border bg-surface shadow-sm overflow-hidden text-center">
        <EmptyState
          title={completionTitle || t("completionTitle")}
          description={completionDescription || t("completionDesc")}
          action={
            completionAction || (
              <div className="flex flex-wrap gap-4 justify-center">
                <Button variant="secondary" onClick={handleRestart} className="flex items-center gap-2">
                  <RotateCcwIcon className="h-4 w-4" />
                  {t("restart")}
                </Button>
                <Button onClick={onClose} className="flex items-center gap-2">
                  <ArrowLeftIcon className="h-4 w-4" />
                  {t("back")}
                </Button>
              </div>
            )
          }
        />
      </div>
    );
  }

  const progressRatio = totalSlides > 1 ? (currentIdx / (totalSlides - 1)) * 100 : 100;
  const isLast = currentIdx === totalSlides - 1;

  return (
    <Card className="w-full max-w-2xl mx-auto border border-border shadow-md overflow-hidden relative text-left">
      {/* Progress bar */}
      <div className="w-full h-2 bg-surface-subtle border-b border-border/40 overflow-hidden relative select-none">
        <div
          className="h-full bg-brand rounded-r-md transition-all duration-[var(--duration-base)] ease-out"
          style={{ width: `${progressRatio}%` }}
          aria-hidden="true"
        />
      </div>

      {/* Header bar controls */}
      <CardHeader className="border-none pb-0 pt-6 flex flex-row items-center justify-between gap-4 select-none">
        <div className="flex items-center gap-2">
          <Badge variant="brand">
            {t("slideCounter", { current: currentIdx + 1, total: totalSlides })}
          </Badge>
          <span className="text-xs font-bold text-fg-muted font-display truncate max-w-xs md:max-w-md">
            {title}
          </span>
        </div>
        
        <button
          type="button"
          onClick={onClose}
          className={cn(
            "tap-target p-2 rounded-lg text-fg-muted hover:text-fg hover:bg-surface-subtle transition-all focus-visible:outline-3 focus-visible:outline-[var(--focus-ring)]"
          )}
          aria-label={t("close")}
        >
          <XIcon className="h-5 w-5" />
        </button>
      </CardHeader>

      <CardContent className="p-8 max-phone:p-6 space-y-6">
        {/* Slide image if any */}
        {currentSlide.imageUrl && (
          <div className="aspect-video w-full bg-surface-subtle border border-border/60 rounded-xl overflow-hidden flex items-center justify-center select-none">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={currentSlide.imageUrl}
              alt={currentSlide.title}
              className="w-full h-full object-cover select-none"
            />
          </div>
        )}

        {/* Slide text */}
        <div className="space-y-3">
          <h2 className="text-2xl font-extrabold text-fg font-display tracking-tight leading-tight max-phone:text-xl">
            {currentSlide.title}
          </h2>
          <p className="text-base text-fg-muted leading-relaxed whitespace-pre-line max-phone:text-sm">
            {currentSlide.description}
          </p>
        </div>
      </CardContent>

      {/* Footer trigger */}
      <CardFooter className="pt-3 pb-6 flex justify-between select-none">
        <Button
          variant="secondary"
          onClick={handlePrev}
          disabled={currentIdx === 0}
          className="flex items-center gap-1.5"
        >
          <ChevronLeftIcon className="h-4 w-4" />
          {t("prev")}
        </Button>

        <Button
          onClick={handleNext}
          className="flex items-center gap-1.5 min-w-32 justify-center"
        >
          {isLast ? (
            <>
              {t("finish")}
              <CheckIcon className="h-4 w-4" />
            </>
          ) : (
            <>
              {t("next")}
              <ChevronRightIcon className="h-4 w-4" />
            </>
          )}
        </Button>
      </CardFooter>
    </Card>
  );
}

// src/components/wizards/SlideWizard.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ArrowLeft, ArrowRight, RotateCcw, CheckCircle2 } from '@lucide/vue'
import { fetchWizardSlides } from '@/lib/api/services'
import SkeletonArticle from '@/components/ui/SkeletonArticle.vue'
import type { SlideDto } from '@/lib/api/types'

const props = defineProps<{
  scenarioId: number
  /** Yakunlash ekranidagi «Qaytish» tugmasi manzili. */
  backTo: string
}>()

const { t } = useI18n()

const slides = ref<SlideDto[]>([])
const loading = ref(true)
const currentIndex = ref(0)
const isFinished = ref(false)

const currentSlide = computed(() => slides.value[currentIndex.value])
const isLast = computed(() => currentIndex.value === slides.value.length - 1)
const progress = computed(() =>
  slides.value.length ? ((currentIndex.value + 1) / slides.value.length) * 100 : 0,
)

function goNext() {
  if (isLast.value) isFinished.value = true
  else currentIndex.value++
}

function restart() {
  currentIndex.value = 0
  isFinished.value = false
}

onMounted(async () => {
  slides.value = (await fetchWizardSlides(props.scenarioId)).sort(
    (a, b) => a.sortOrder - b.sortOrder,
  )
  loading.value = false
})
</script>

<template>
  <SkeletonArticle v-if="loading" :lines="4" />

  <div
    v-else-if="slides.length === 0"
    class="p-8 sm:p-12 rounded-3xl bg-[var(--surface)] border border-[var(--border-default)] shadow-xl text-center text-[var(--fg-muted)]"
  >
    {{ t('slidePages.empty') }}
  </div>

  <!-- --- Yakunlash ekrani --- -->
  <div
    v-else-if="isFinished"
    class="p-8 sm:p-12 rounded-3xl bg-[var(--surface)] border border-[var(--border-default)] shadow-xl text-center space-y-6"
    role="status"
  >
    <div
      class="w-20 h-20 mx-auto rounded-full bg-emerald-500/10 text-emerald-600 flex items-center justify-center"
    >
      <CheckCircle2 class="w-10 h-10" aria-hidden="true" />
    </div>
    <h2 class="text-2xl font-extrabold text-[var(--fg)] font-display">
      {{ t('slides.completionTitle') }}
    </h2>
    <p class="text-base text-[var(--fg-muted)] leading-relaxed font-light max-w-lg mx-auto">
      {{ t('slides.completionDesc') }}
    </p>
    <div class="flex flex-wrap items-center justify-center gap-3 pt-2">
      <button
        type="button"
        class="inline-flex items-center gap-2 px-8 py-3.5 rounded-xl bg-[var(--brand)] text-[var(--fg-on-brand)] font-bold hover:opacity-90 transition-all cursor-pointer"
        @click="restart"
      >
        <RotateCcw class="w-4 h-4" aria-hidden="true" />
        <span>{{ t('slides.restart') }}</span>
      </button>
      <router-link
        :to="backTo"
        class="px-8 py-3.5 rounded-xl border border-[var(--border-default)] text-[var(--fg)] font-bold hover:bg-[var(--surface-subtle)] transition-all"
      >
        {{ t('slides.back') }}
      </router-link>
    </div>
  </div>

  <!-- --- Slayd --- -->
  <div
    v-else-if="currentSlide"
    class="rounded-3xl bg-[var(--surface)] border border-[var(--border-default)] shadow-xl overflow-hidden"
  >
    <div
      class="h-2 bg-[var(--surface-muted)]"
      role="progressbar"
      :aria-valuenow="currentIndex + 1"
      aria-valuemin="1"
      :aria-valuemax="slides.length"
    >
      <div class="h-full bg-[var(--brand)] transition-all" :style="{ width: `${progress}%` }" />
    </div>

    <div class="p-6 sm:p-10 space-y-6">
      <div class="flex items-center justify-between gap-4">
        <h2 class="text-2xl font-extrabold text-[var(--fg)] font-display">
          {{ currentSlide.title }}
        </h2>
        <span class="shrink-0 text-xs font-bold text-[var(--brand)] tabular-nums">
          {{ t('slides.slideCounter', { current: currentIndex + 1, total: slides.length }) }}
        </span>
      </div>

      <img
        v-if="currentSlide.imageUrl"
        :src="currentSlide.imageUrl"
        :alt="currentSlide.title"
        class="w-full max-h-80 object-contain rounded-2xl bg-[var(--surface-subtle)]"
      />

      <p
        v-if="currentSlide.content"
        class="text-base text-[var(--fg-muted)] leading-relaxed font-light whitespace-pre-line"
      >
        {{ currentSlide.content }}
      </p>

      <div class="flex items-center justify-between gap-4 pt-2">
        <button
          type="button"
          class="inline-flex items-center gap-2 px-6 py-2.5 rounded-xl border border-[var(--border-default)] font-bold text-sm text-[var(--fg)] disabled:opacity-30 disabled:cursor-not-allowed cursor-pointer"
          :disabled="currentIndex === 0"
          @click="currentIndex--"
        >
          <ArrowLeft class="w-4 h-4" aria-hidden="true" />
          <span>{{ t('slides.prev') }}</span>
        </button>
        <button
          type="button"
          class="inline-flex items-center gap-2 px-6 py-2.5 rounded-xl bg-[var(--brand)] text-[var(--fg-on-brand)] font-bold text-sm hover:opacity-90 transition-all cursor-pointer"
          @click="goNext"
        >
          <span>{{ isLast ? t('slides.finish') : t('slides.next') }}</span>
          <ArrowRight class="w-4 h-4" aria-hidden="true" />
        </button>
      </div>
    </div>
  </div>
</template>
